version: "3.9"
   
services:
  web:
    build: .
    env_file:
      - ./.env
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8001
    restart: always
    volumes:
      - .:/code
    ports:
      - "8001:8001"
