version: "3.9"
   
services:
  web:
    build: .
    env_file:
      - ./.env
    tty: true
    command: python3 ./manage.py runserver 0:8005
    restart: always
    volumes:
      - .:/code
    ports:
      - "8005:8005"
networks:
  frontend:
    driver: nginxproxymanager_default
