version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - /home/marbrume/data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    env_file:
      - ./.env
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8001
    restart: always
    volumes:
      - .:/code
    ports:
      - "8001:8001"
    depends_on:
      - db
